//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace NLappCMS.Models
{
	/// <summary>Welkom</summary>
	[PublishedContentModel("welkom")]
	public partial class Welkom : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "welkom";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Welkom(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Welkom, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Sitename: Used on the homepage as well as the title and social cards
		///</summary>
		[ImplementPropertyType("sitename")]
		public string Sitename
		{
			get { return this.GetPropertyValue<string>("sitename"); }
		}

		///<summary>
		/// Subtitel
		///</summary>
		[ImplementPropertyType("subtitel")]
		public string Subtitel
		{
			get { return this.GetPropertyValue<string>("subtitel"); }
		}

		///<summary>
		/// Voorwaarden
		///</summary>
		[ImplementPropertyType("voorwaarden")]
		public Our.Umbraco.Vorto.Models.VortoValue Voorwaarden
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("voorwaarden"); }
		}
	}
}
